# Generated by Django 4.2.30 on 2026-05-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_created_by_student_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='student',
            name='serial_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
