# Generated by Django 4.2.30 on 2026-05-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_date_of_birth_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='serial_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('academic_year', 'serial_number')},
        ),
    ]
