# Generated by Django 4.2.30 on 2026-05-22 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dearness_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('annual_compulsory', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='students.academicyear')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='students.schoolclass')),
            ],
            options={
                'unique_together': {('academic_year', 'school_class')},
            },
        ),
        migrations.CreateModel(
            name='FeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dearness_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, help_text='New students only', max_digits=10)),
                ('miscellaneous_dues', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('admission_fee', models.DecimalField(decimal_places=2, default=0, help_text='New students only', max_digits=10)),
                ('annual_compulsory', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collection_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('upi', 'UPI'), ('bank', 'Bank Transfer')], default='cash', max_length=10)),
                ('cheque_number', models.CharField(blank=True, default='', max_length=30)),
                ('receipt_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_records', to='students.academicyear')),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_fees', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_records', to='students.student')),
            ],
            options={
                'ordering': ['-collection_date'],
                'unique_together': {('student', 'academic_year', 'month')},
            },
        ),
    ]
