# Generated by Django 4.2.30 on 2026-05-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_feestructure_miscellaneous_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='feerecord',
            name='received_by',
            field=models.CharField(choices=[('sangeeta', 'Mrs. Sangeeta Sahu (Treasurer, SMWS)'), ('neelam', 'Mrs. Neelam Gupta (Sr. Teacher)'), ('other', 'Other')], default='sangeeta', max_length=20),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='received_by_other',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
